### PR TITLE
Add Github Actions workflow to run Composer and PHPUnit

### PR DESCRIPTION
**Pull request by bdsl**
PHPUnit tests currently appear to be failing. I'm not attempting to fix that here, simply making it more visible. It would probably be worth fixing that soon as part of a separate issue. The output can be seen in the github actions log, but I have avoided failing the build - I think intentionally failing the build is very rarely useful and failures should represent mistakes that can be immediately fixed.

### CODE REVIEW

**Comment by bdsl** [comment]
No build here just yet - I believe github actions won't be enabled until this is merged. But you can see the build on my fork by clicking the green ticks at https://github.com/bdsl/phalyfusion/commits/master

**Comment by koninka** [comment]
@bdsl Have you tried the tests locally? Are they passed?

**Comment by koninka** [comment]
@bdsl I've decided to merge this PR and check it by myself

**Comment by bdsl** [comment]
@koninka Yes, the tests fail for me locally, same as in the action. I actually just pushed another commit https://github.com/bdsl/phalyfusion/commit/e9393a6ba5dba8ff41049b33bbb0548d2f11991c a moment ago after I spotted the makefile.

**Pull request merged**
